Fix syntax error in dhclient-script
Fix syntax error introduced by
e92daeac67760539565fb526aff0b3a97cc8d6ad dhclient-script: IPv6 was used
only sometimes in /etc/resolv.conf.

Error msg:
"dhclient: /sbin/dhclient-script: 65: /sbin/dhclient-script: Syntax
error: "elif" unexpected"

Change-Id: I67fc90780ac2ad77c607433908bd71b819099a34